In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

**Train Test Split**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

**Scaling**

In [ ]:
scale = StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.transform(X_test)

In [ ]:
X_train

array([[ 1.65885397,  0.21269666,  1.61070859, ...,  0.7154586 ,
        -0.57270985,  0.39259685],
       [-0.28467083,  0.57534129, -0.28172447, ...,  0.70627232,
         1.25871753,  0.65870024],
       [-0.60280733, -1.38293969, -0.6003484 , ..., -0.62221723,
        -0.2013015 , -0.20585975],
       ...,
       [ 0.66684652,  0.17760202,  0.72074451, ...,  1.36156046,
         0.23574367,  0.60404415],
       [-1.03662982,  0.20333809, -0.92275048, ...,  0.48886363,
        -0.49586674,  1.97375893],
       [-0.75609128, -2.01932251, -0.7724641 , ..., -1.03223163,
         0.77364542, -0.54704626]])

In [ ]:
y_train

517    M
44     M
529    B
534    B
87     M
      ..
192    B
400    M
177    M
376    B
313    B
Name: diagnosis, Length: 455, dtype: object

**Label Encoder**

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0])

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

### **Define a Model**

In [ ]:
class MyNuralNetwork(torch.nn.Module):
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
      # Clamp predictions to avoid log(0)
      epsilon = 1e-7
      y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

      # Calculate loss
      loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
      return loss

In [ ]:
learning_rate = 0.1
epochs = 25

### **Training Pipeline**

In [ ]:
# create a model

model = MyNuralNetwork(X_train_tensor)

# define in loop
for(epoch) in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # calculate loss
  loss = model.loss_function(y_pred,y_train_tensor)

  # backward pass
  loss.backward()

  # upadte weights
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.438781505228209
Epoch: 2, Loss: 3.3050901230239136
Epoch: 3, Loss: 3.1710554490625342
Epoch: 4, Loss: 3.0310973230340457
Epoch: 5, Loss: 2.8865127395252355
Epoch: 6, Loss: 2.736751718725913
Epoch: 7, Loss: 2.587865471897722
Epoch: 8, Loss: 2.430052902272586
Epoch: 9, Loss: 2.275121874045224
Epoch: 10, Loss: 2.1203871230941673
Epoch: 11, Loss: 1.9689815704321787
Epoch: 12, Loss: 1.8242650568576921
Epoch: 13, Loss: 1.6877549585450482
Epoch: 14, Loss: 1.5554774957541355
Epoch: 15, Loss: 1.4330032440858704
Epoch: 16, Loss: 1.3205261573086085
Epoch: 17, Loss: 1.2223077697860332
Epoch: 18, Loss: 1.1365728371384578
Epoch: 19, Loss: 1.066029984933587
Epoch: 20, Loss: 1.0093305648191522
Epoch: 21, Loss: 0.9644472556227597
Epoch: 22, Loss: 0.9290433346984754
Epoch: 23, Loss: 0.9008789635915815
Epoch: 24, Loss: 0.8780803130442435
Epoch: 25, Loss: 0.8592193091384585

In [ ]:
model.weights

tensor([[-0.1277],
        [-0.2577],
        [ 0.2006],
        [ 0.3877],
        [-0.1101],
        [ 0.0690],
        [-0.0408],
        [ 0.0093],
        [ 0.2620],
        [ 0.4142],
        [-0.2621],
        [ 0.5504],
        [ 0.3674],
        [ 0.4442],
        [-0.2131],
        [-0.3186],
        [ 0.2188],
        [ 0.1565],
        [ 0.6278],
        [-0.3106],
        [-0.2740],
        [ 0.2347],
        [-0.2749],
        [-0.1445],
        [-0.0094],
        [-0.2046],
        [ 0.3891],
        [-0.4116],
        [ 0.0926],
        [-0.0195]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1168], dtype=torch.float64, requires_grad=True)

### **Evaluation**

In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9 ).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6334256529808044